kind: ConfigMap
apiVersion: v1
metadata:
  name: mongodb-configmap
  namespace: default
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
  ensure-user.js: |
    db.createUser(
      {
        user: "userteam33",
        pwd: "passwordteam33",
        roles: [
          { role: "userAdminAnyDatabase", db: "admin" },
          { role: "readWriteAnyDatabase", db: "admin" },
          { role: "dbAdminAnyDatabase", db: "admin" },
          { role: "clusterAdmin", db: "admin" }
        ]
      }
    )