apiVersion: apps/v1

kind: Deployment # mongodb deployment
metadata:
 name: redis-deployment
 labels:
   app: redis
spec:
 replicas: 1
 selector:
   matchLabels:
     app: redis
 template:
   metadata:
     labels:
       app: redis
   spec: # mongodb deployment spec
     containers:
       - name: redis-container
         image: redis:6 # mongo image name
         ports: # mongodb container ports
         - containerPort: 27017